spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/java?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: lsf51938
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  # mapper映射文件
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.blog.entity
  #开启驼峰uName自动映射到u_name
  map-underscore-to-camel-case: true
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


# 打印sql
logging:
  level:
    com.blog.dao.impl : debug